
# Config fixes for Neovim (See :checkhealth)
set-option -sg escape-time 10
set-option -g focus-events on

# Image support for Neovim (Kitty Graphics Protocol)
# Needs Tmux >= 3.3
set -gq allow-passthrough on

# lua/plugins/images.lua:
# Uncomment the following line to support 3rd/image.nvim's `tmux_show_only_in_active_window = true`.
# Visual activity reporting can be very useful for beeping on completion of long running applications so it is not disabled by default.
# set -g visual-activity off

set -g @jst-nvim-tmux-conf-loaded ""
